marvel_heroes_with_hints = [
    ("doctorstrange", "Master of the Mystic Arts and the Sorcerer Supreme."),
    ("ironman", "Genius billionaire in an armored suit powered by an arc reactor."),
    ("captainamerica", "Super-soldier with a shield made of vibranium."),
    ("thor", "The god of thunder who wields the hammer Mjolnir."),
    ("hulk", "A scientist who transforms into a green rage monster with immense strength."),
    ("blackwidow", "A highly trained spy and combat expert."),
    ("spiderman", "A young hero with spider-like abilities and web-slinging."),
    ("antman", "Can shrink and grow in size using a special suit."),
    ("hawkeye", "A master archer with precise aim."),
    ("blackpanther", "King of Wakanda with enhanced senses and a vibranium suit."),
    ("scarletwitch", "Possesses powerful chaos magic and reality-warping abilities."),
    ("vision", "An android with the power of flight, density control, and a mind stone."),
    ("falcon", "Uses mechanical wings for flight and is an expert in aerial combat."),
    ("wintersoldier", "A super-soldier with a metal arm and highly trained combat skills."),
    ("captainmarvel", "Possesses cosmic powers and can fly through space."),
    ("starlord", "Leader of the Guardians of the Galaxy, with combat and piloting skills."),
    ("groot", "A sentient tree-like creature with regenerative powers."),
    ("rocketraccoon", "A genetically enhanced raccoon with tech expertise and a love for weapons."),
    ("drax", "A powerful warrior with a personal vendetta against Thanos."),
    ("gamora", "A skilled assassin and the adopted daughter of Thanos."),
    ("nebula", "A cybernetic assassin with a complex relationship with her sister, Gamora."),
    ("loki", "The god of mischief, known for illusion and trickery."),
    ("warmachine", "A military officer in a heavily armed Iron Man-style suit."),
    ("wasp", "A superhero with the ability to shrink and fly, alongside Ant-Man."),
    ("shangchi", "Master of martial arts and the mystical Ten Rings."),
    ("eternals", "An ancient group of immortal beings with various powers.")
]

