marvel_heroes_with_hints = [
    ("doctorstrange", "Master of the Mystic Arts and the Sorcerer Supreme."),
    ("ironman", "Genius billionaire in an armored suit powered by an arc reactor."),
    ("captainamerica", "Super-soldier with a shield made of vibranium."),
    ("thor", "The god of thunder who wields the hammer Mjolnir."),
    ("hulk", "A scientist who transforms into a green rage monster with immense strength."),
    ("blackwidow", "A highly trained spy and combat expert."),
    ("spiderman", "A young hero with spider-like abilities and web-slinging."),
    ("antman", "Can shrink and grow in size using a special suit."),
    ("hawkeye", "A master archer with precise aim."),
    ("blackpanther", "King of Wakanda with enhanced senses and a vibranium suit."),
    ("scarletwitch", "Possesses powerful chaos magic and reality-warping abilities."),
    ("vision", "An android with the power of flight, density control, and a mind stone."),
    ("falcon", "Uses mechanical wings for flight and is an expert in aerial combat."),
    ("wintersoldier", "A super-soldier with a metal arm and highly trained combat skills."),
    ("captainmarvel", "Possesses cosmic powers and can fly through space."),
    ("starlord", "Leader of the Guardians of the Galaxy, with combat and piloting skills."),
    ("groot", "A sentient tree-like creature with regenerative powers."),
    ("rocketraccoon", "A genetically enhanced raccoon with tech expertise and a love for weapons."),
    ("drax", "A powerful warrior with a personal vendetta against Thanos."),
    ("gamora", "A skilled assassin and the adopted daughter of Thanos."),
    ("nebula", "A cybernetic assassin with a complex relationship with her sister, Gamora."),
    ("loki", "The god of mischief, known for illusion and trickery."),
    ("warmachine", "A military officer in a heavily armed Iron Man-style suit."),
    ("wasp", "A superhero with the ability to shrink and fly, alongside Ant-Man."),
    ("shangchi", "Master of martial arts and the mystical Ten Rings."),
    ("eternals", "An ancient group of immortal beings with various powers.")
]

bollywood_heroes_with_hints = [
    ("shahrukhkhan", "Known as the King of Bollywood, famous for 'Dilwale Dulhania Le Jayenge'."),
    ("salmankhan", "Star of 'Bajrangi Bhaijaan' and 'Sultan'."),
    ("aamirkhan", "Actor in 'Dangal' and '3 Idiots', known for perfection."),
    ("akshaykumar", "Known for action-comedies like 'Housefull' and 'Khiladi'."),
    ("ranveersingh", "A versatile actor known for energetic roles in 'Padmaavat' and 'Gully Boy'."),
    ("hrithikroshan", "A dancing sensation and action star from 'Krrish' and 'War'."),
    ("ranbirkapoor", "Known for roles in 'Sanju' and 'Rockstar'."),
    ("ajaydevgn", "A serious and action-packed actor famous for 'Singham' and 'Tanhaji'."),
    ("amitabhbachchan", "The legendary actor known for 'Sholay' and 'Piku'."),
    ("varundhawan", "Star of 'Badrinath Ki Dulhania' and 'Street Dancer'."),
    ("sidharthmalhotra", "Known for his roles in 'Kapoor & Sons' and 'Shershaah'."),
    ("arjunkapoor", "Notable for performances in '2 States' and 'Namaste England'."),
    ("akshaye", "Famous for his roles in 'Sardar Udham' and 'Pati Patni Aur Woh'."),
    ("karthikaryan", "Known for his roles in 'Pyaar Ka Punchnama' and 'Sonu Ke Titu Ki Sweety'."),
    ("sushantsinghrajput", "Known for 'Chhichhore' and 'MS Dhoni: The Untold Story'."),
    ("saifalikhan", "Famous for roles in 'Omkara' and 'Tanhaji'."),
    ("johnabraham", "Known for his roles in 'Dhoom' and 'Batla House'."),
    ("vivekoberoi", "Notable for his performances in 'Company' and 'Saathiya'."),
    ("emraanhashmi", "Known for his roles in 'Murder' and 'Jannat'."),
    ("shahidkapoor", "Famous for 'Haider' and 'Kabir Singh'."),
    ("hritikroshan", "Renowned for his performances in 'War' and 'Super 30'."),
    ("abhishekbachchan", "Notable for 'Guru' and 'Dhoom'."),
    ("bobbydeol", "Known for roles in 'Soldier' and 'Race 3'."),
    ("sushantsinghrajput", "Famous for his roles in 'Chhichhore' and 'MS Dhoni: The Untold Story'."),
    ("diljeitsingh", "Popular for his roles in 'Punjab 1984' and 'Good Newwz'."),
    ("prabhas", "Known for his work in 'Baahubali' and 'Saaho'."),
    ("nawazuddinsiddiqui", "Renowned for his performances in 'Gangs of Wasseypur' and 'Sacred Games'."),
    ("manojbajpayee", "Famous for his roles in 'Satya' and 'The Family Man'."),
    ("pankajtripathi", "Known for his roles in 'Stree' and 'Mirzapur'."),
    ("zaynmalik", "Not a Bollywood actor but a well-known figure in the entertainment industry."),
    ("salman", "Another name for Salman Khan, star of 'Kick' and 'Bajrangi Bhaijaan'."),
    ("ranvirsingh", "Another spelling for Ranveer Singh, known for 'Padmaavat' and 'Gully Boy'."),
    ("ranbirkapoor", "Another spelling for Ranbir Kapoor, known for 'Rockstar' and 'Sanju'."),
    ("ajay", "Another name for Ajay Devgn, known for 'Tanhaji' and 'Singham'."),
    ("amitabh", "Another name for Amitabh Bachchan, renowned for his roles in 'Sholay' and 'Paa'.")
]

cricketers_with_hints = [
    ("sachintendulkar", "The 'Master Blaster' from India – all-time highest run-scorer in international cricket and an IPL champion with Mumbai Indians."),
    ("viratkohli", "India's run-machine – former captain with the most runs in T20Is, leading Royal Challengers Bangalore in IPL."),
    ("msdhoni", "India's legendary wicketkeeper-captain – led India to multiple ICC trophies and Chennai Super Kings to four IPL titles."),
    ("rohitsharma", "The Hitman from India – only cricketer with three ODI double centuries and captain of Mumbai Indians, leading them to five IPL titles."),
    ("kapildev", "India's 1983 World Cup-winning captain – a legendary all-rounder, though he never played in IPL."),
    ("yuvrajsingh", "The Indian hero – hit six sixes in one over in T20 World Cup 2007, played for various IPL teams including Mumbai Indians."),
    ("rahuldravid", "The Wall of Indian cricket – known for his technique, now a coach for Rajasthan Royals in IPL after his legendary international career."),
    ("anilkumble", "India's spin magician – former captain and India’s highest wicket-taker, also coached Punjab Kings in IPL."),
    ("jaspritbumrah", "India's death-over specialist – known for his pinpoint yorkers and a key player for Mumbai Indians in IPL."),
    ("hardikpandya", "India's explosive all-rounder – led Gujarat Titans to their first IPL title in 2022."),
    ("ravindrajadeja", "India's versatile all-rounder – exceptional fielder and match-winner, plays for Chennai Super Kings."),
    ("souravganguly", "The Prince of Kolkata from India – transformed Indian cricket, and former captain of Kolkata Knight Riders in IPL."),
    ("zaheerkhan", "India's swing king – instrumental in the 2011 World Cup win, former player and mentor of Mumbai Indians."),
    ("vvslaxman", "India’s elegant middle-order batsman – played for Deccan Chargers in IPL and known for his heroic match-saving innings."),
    ("klrahul", "India's stylish opener – captain of Lucknow Super Giants and known for his consistency with the bat in IPL."),
    ("shikhardhawan", "Gabbar of India – leading run-scorer for Punjab Kings in IPL, with a penchant for big tournament runs."),
    ("sureshraina", "India's Mr. IPL – a key player for Chennai Super Kings, known for his aggressive batting and fielding."),
    ("dineshkarthik", "India's reliable wicketkeeper-batsman – currently with Royal Challengers Bangalore, known for his finishing skills."),
    ("rishabhpant", "India's fearless wicketkeeper-batsman – captain of Delhi Capitals and known for his explosive performances."),
    ("ashwinravichandran", "India’s off-spin wizard – now playing for Rajasthan Royals, known for his tactical brilliance in IPL."),
    ("bhuvneshwar", "India’s swing expert – a key bowler for Sunrisers Hyderabad, known for his ability to control the new ball."),
    ("rashidkhan", "Afghanistan’s star leg-spinner – a T20 sensation and crucial player for Gujarat Titans in IPL."),
    ("andrerussell", "West Indian powerhouse – famous for his all-round performances for Kolkata Knight Riders in IPL."),
    ("davidwarner", "Australia’s explosive opener – a former captain of Sunrisers Hyderabad, leading them to their first IPL title in 2016."),
    ("abdevilliers", "South Africa’s Mr. 360 – a fan favorite for Royal Challengers Bangalore, known for his innovative shots."),
    ("benstokes", "England’s star all-rounder – key player in ICC World Cup 2019 win and now a member of Chennai Super Kings in IPL."),
    ("patcummins", "Australia’s fast-bowling spearhead – known for his pace, he has been part of Kolkata Knight Riders."),
    ("jofraarcher", "England’s pace sensation – known for his searing speed, playing for Mumbai Indians in IPL."),
    ("kieronpollard", "West Indies’ powerful all-rounder – a long-time match-winner for Mumbai Indians."),
    ("quintondekock", "South Africa’s dynamic wicketkeeper-batsman – currently plays for Lucknow Super Giants."),
    ("stevesmith", "Australia’s batting maestro – a technically sound player, formerly captain of Rajasthan Royals."),
    ("kanewilliamson", "New Zealand’s calm leader – former captain of Sunrisers Hyderabad, known for his class and consistency."),
    ("sunilnarine", "West Indies’ mystery spinner – a vital player for Kolkata Knight Riders with his spin and pinch-hitting."),
    ("trentboult", "New Zealand’s left-arm quick – a key player for Rajasthan Royals, known for his swing bowling."),
    ("shreyasiyer", "India’s young captain – led Delhi Capitals to their first IPL final in 2020."),
    ("mayankagarwal", "India’s reliable opener – former captain of Punjab Kings, known for his consistency."),
    ("prithvishaw", "India’s aggressive opener – a crucial player for Delhi Capitals in IPL."),
    ("sanjusamson", "India’s exciting wicketkeeper-batsman – captain of Rajasthan Royals with a flair for big innings."),
    ("ravibishnoi", "India’s promising leg-spinner – impressed with his skills for Lucknow Super Giants."),
    ("arshdeep", "India’s emerging left-arm fast bowler – known for his death bowling for Punjab Kings."),
    ("devduttpadikkal", "India’s young left-handed opener – made waves with Royal Challengers Bangalore, now with Rajasthan Royals.")
]


indian_cities_with_hints = [
    ("mumbai", "Financial Capital Of India"),
    ("delhi", "Capital Of India"),
    ("bengaluru", "Silicon Valley Of India"),
    ("chennai", "Gateway To South India"),
    ("hyderabad", "City Of Pearls"),
    ("kolkata", "City Of Joy"),
    ("pune", "Oxford Of The East"),
    ("ahmedabad", "Textile Hub Of India"),
    ("jaipur", "Pink City Of Rajasthan"),
    ("surat", "Diamond City"),
    ("lucknow", "City Of Nawabs"),
    ("chandigarh", "Planned City"),
    ("varanasi", "Spiritual Capital Of India"),
    ("amritsar", "Golden Temple City"),
    ("thiruvananthapuram", "Evergreen City Of India"),
    ("kochi", "Queen Of The Arabian Sea"),
    ("mysuru", "City Of Palaces"),
    ("indore", "Cleanest City"),
    ("guwahati", "Gateway To Northeast"),
    ("nagpur", "Orange City"),
    ("patna", "Ancient City"),
    ("bhopal", "City Of Lakes"),
    ("agra", "City Of The Taj Mahal"),
    ("shimla", "Queen Of Hills"),
    ("coimbatore", "Manchester Of India"),
    ("udaipur", "City Of Lakes In Rajasthan"),
    ("vadodara", "Cultural Capital Of Gujarat"),
    ("rajkot", "City Of Saurashtra"),
    ("jodhpur", "Blue City, Mehrangarh Fort"),
    ("madurai", "Temple City, Meenakshi Temple"),
    ("nashik", "Winery Of India, Trimbakeshwar Temple"),
    ("kanpur", "Leather City"),
    ("allahabad", "City Of Triveni, Sangam"),
    ("tiruchirappalli", "Rockfort City, Srirangam Temple"),
    ("aurangabad", "City Of Gates, Ajanta And Ellora Caves"),
    ("ranchi", "City Of Falls, Hundru Falls"),
    ("jamshedpur", "Steel City, Jubilee Park"),
    ("dhanbad", "Coal Capital Of India"),
    ("dehradun", "Doon Valley, Forest Research Institute"),
    ("raipur", "Capital Of Chhattisgarh"),
    ("noida", "IT City"),
    ("ghaziabad", "Industrial Hub Of UP"),
    ("vijayawada", "Business Capital Of Andhra Pradesh"),
    ("visakhapatnam", "City Of Density, RK Beach"),
    ("gwalior", "City Of Forts, Gwalior Fort"),
    ("ludhiana", "Manchester Of India"),
    ("meerut", "Sports Goods Manufacturing Hub"),
    ("salem", "Mangoes And Steel City, Yercaud"),
    ("jabalpur", "City Of Marble, Marble Rocks"),
    ("belagavi", "Sugar Bowl, Kittur Fort"),
    ("rourkela", "Steel City Of Odisha, Hanuman Vatika"),
    ("ajmer", "Holy City, Ajmer Sharif Dargah"),
    ("pondicherry", "French Riviera Of The East, Auroville"),
    ("srinagar", "Paradise On Earth, Dal Lake"),
    ("leh", "Highest Settlement, Pangong Lake"),
    ("shillong", "Scotland Of The East, Elephant Falls"),
    ("imphal", "Jewel Of India, Loktak Lake"),
    ("aizawl", "Land Of Highlanders"),
    ("gangtok", "Buddhist Pilgrimage, Rumtek Monastery")
]

indian_historical_places_with_hints = [
    ("tajmahal", "Agra - Built By Shah Jahan In Memory Of Mumtaz"),
    ("redfort", "Delhi - Mughal Residence And Military Headquarters"),
    ("qutubminar", "Delhi - Tallest Brick Minaret In The World"),
    ("indiagate", "Delhi - War Memorial For Soldiers Of World War I"),
    ("gatewayofindia", "Mumbai - Commemorates King George V's Visit To India"),
    ("amerfort", "Jaipur - Known For Its Artistic Hindu Architecture"),
    ("hawamahal", "Jaipur - Palace Of Winds With 953 Windows"),
    ("victoriamemorial", "Kolkata - Memorial To Queen Victoria Of Britain"),
    ("charminar", "Hyderabad - Built To Commemorate The End Of A Plague"),
    ("suntemple", "Konark - 13th Century Temple Dedicated To The Sun God"),
    ("khajurahotemples", "Madhya Pradesh - Famous For Erotic Sculptures"),
    ("sanchistupa", "Madhya Pradesh - Built By Emperor Ashoka, Buddhist Relic"),
    ("ajantacaves", "Maharashtra - Ancient Buddhist Cave Paintings And Sculptures"),
    ("elloracaves", "Maharashtra - Rock-Cut Temples And Monasteries"),
    ("mehraulianarchaeologicalpark", "Delhi - Contains Ruins From Several Historical Eras"),
    ("golcondafort", "Hyderabad - Known For Its Acoustic Effects"),
    ("mysorepalace", "Mysuru - Former Residence Of Wodeyar Dynasty"),
    ("fatehpursikri", "Uttar Pradesh - Mughal Emperor Akbar's Capital City"),
    ("raniikavav", "Gujarat - UNESCO World Heritage Stepwell"),
    ("chittorgarhfort", "Rajasthan - Largest Fort In India, Known For Its History Of Valor"),
    ("jallianwalabagh", "Amritsar - Site Of The 1919 Massacre During British Rule"),
    ("brihadeeswarartemple", "Tamil Nadu - Chola Dynasty Temple, UNESCO Site"),
    ("gwaliorfort", "Madhya Pradesh - Historic Fort With Intricate Architecture"),
    ("ranthamborefort", "Rajasthan - Famous Fort Inside A Wildlife Sanctuary"),
    ("elephantacaves", "Mumbai - Ancient Hindu Cave Sculptures"),
    ("ruinsofhampi", "Karnataka - Ancient City, Capital Of Vijayanagara Empire"),
    ("jantarmantar", "Jaipur - Collection Of Astronomical Instruments"),
    ("sabarmatiashram", "Ahmedabad - Mahatma Gandhi's Home And Headquarters"),
    ("nalanduniversity", "Bihar - Ancient Center Of Learning And Buddhism"),
    ("golgumbaz", "Bijapur - Second Largest Dome In The World"),
    ("jogfalls", "Karnataka - One Of The Highest Waterfalls In India"),
    ("cellularjail", "Andaman Islands - Used By British For Political Prisoners"),
    ("raghuwarfort", "Chhattisgarh - Historic Fort With Rich History"),
    ("badshahibagh", "Agra - Mughal Garden With Beautiful Landscapes"),
    ("durgabari", "Silchar - Historical Temple Dedicated To Goddess Durga"),
    ("srirangamtemple", "Tiruchirappalli - Famous Vaishnavite Temple Complex"),
    ("madhuratemple", "Kerala - Temple Known For Its Architectural Splendor"),
    ("seemachalamtemple", "Visakhapatnam - Ancient Temple Dedicated To Varaha Lakshmi Narasimha"),
    ("kumbhalgarhfort", "Rajasthan - Known For Its Impressive Fortifications"),
    ("sahastra lingatemple", "Bagalkot - Temple With Thousand Lingas"),
    ("shantiastupa", "Rajgir - Buddhist Stupa Built By The Japanese"),
    ("rajarani temple", "Bhubaneswar - Ancient Hindu Temple Known For Its Architecture"),
    ("kailasanathtemple", "Kanchipuram - Historic Temple From The Pallava Dynasty"),
    ("sabarimala", "Kerala - Famous Pilgrimage Site In The Western Ghats"),
    ("siddhivinayaktemple", "Mumbai - Popular Ganesh Temple"),
    ("krishna temple", "Udupi - Important Pilgrimage Site For Followers Of Krishna"),
    ("ahmedshahi", "Jaipur - Mughal Period Monument Known For Its Historical Importance"),
    ("pattadakal", "Karnataka - UNESCO World Heritage Site With Chalukyan Temples"),
    ("raigadh", "Maharashtra - Fort Associated With Chhatrapati Shivaji Maharaj"),
    ("shillong", "Shillong - Famous For Its Beautiful Waterfalls"),
    ("mandu", "Madhya Pradesh - Fort City With Rich Historical Significance"),
    ("kalapathar", "Andaman - Known For Its Scenic Beauty And Historical Importance")
]

indian_cuisines_with_hints = [
    ("biryani", "A RICE DISH WITH SPICES, ORIGINATING FROM HYDERABAD"),
    ("samosa", "FRIED PASTRY FILLED WITH SPICED POTATOES"),
    ("dosa", "A TYPE OF THIN CREPE FROM SOUTH INDIA"),
    ("butterchicken", "CREAMY CHICKEN CURRY FROM PUNJAB"),
    ("idli", "STEAMED RICE CAKES FROM SOUTH INDIA"),
    ("paneerbuttermasala", "COTTAGE CHEESE IN A CREAMY TOMATO SAUCE"),
    ("cholebhature", "SPICY CHICKPEAS SERVED WITH FRIED BREAD"),
    ("pavbhaji", "MIXED VEGETABLE CURRY SERVED WITH BUTTERED BREAD"),
    ("dalmakhani", "LENTIL DISH FROM PUNJAB, COOKED WITH BUTTER"),
    ("vada", "SPICY DEEP FRIED SNACK FROM SOUTH INDIA"),
    ("ragdapattice", "SPICY POTATO CAKES WITH A CHICKPEA CURRY"),
    ("kebab", "GRILLED MEAT OR VEGETABLES MARINATED IN SPICES"),
    ("kheer", "SWEET RICE PUDDING COOKED WITH MILK AND DRIED FRUITS"),
    ("poha", "FLATTENED RICE COOKED WITH SPICES AND VEGETABLES"),
    ("pulao", "RICE DISH COOKED WITH SPICES AND VEGETABLES"),
    ("kulfi", "INDIAN ICE CREAM MADE WITH MILK AND FLAVORS"),
    ("bhelpuri", "PUFFED RICE MIXED WITH VEGETABLES AND CHUTNEYS"),
    ("aalotikki", "SPICY POTATO PATTIES OFTEN SERVED WITH CHUTNEY"),
    ("panchmeldal", "MIXED LENTIL CURRY FROM RAJASTHAN"),
    ("daltadka", "LENTIL DISH TEMPERED WITH SPICES AND GHEE"),
    ("aalogobhi", "POTATO AND CAULIFLOWER CURRY"),
    ("kachori", "SPICY FILLED PASTRY OFTEN SERVED AS A SNACK"),
    ("misalpav", "SPICY BEAN CURRY SERVED WITH BREAD"),
    ("khichdi", "RICE AND LENTIL DISH COOKED TOGETHER"),
    ("tandoorichicken", "CHICKEN MARINATED IN YOGURT AND SPICES THEN GRILLED"),
    ("pithla", "SPICY GRAM FLOUR CURRY FROM MAHARASHTRA"),
    ("dhokla", "STEAMED SAVORY CAKE FROM GUJARAT"),
    ("kothimbirvadi", "CORIANDER AND SPICE FLAVORED SNACK FROM MAHARASHTRA"),
    ("prawncurry", "SPICY CURRY MADE WITH PRAWNS"),
    ("sambhar", "TANGY LENTIL STEW FROM SOUTH INDIA"),
    ("khoya", "MILK SOLIDS USED IN SWEETS AND DESSERTS")
]

loss_replies = [
    "Arre yaar, ek aur zindagi chali gayi! Lagta hai aapko game ka 'cheat code' dekhna padega. 😂",
    "Oye hoye! Aapne ek aur zindagi kho di. Lagta hai aapko game ki 'kismat' ko dekhna padega. 😆",
    "Arre bhai, ek life chali gayi! Lagta hai aapko abhi thoda 'dhamaal' karna padega. 😜",
    "Hawww! Ek aur zindagi kho gayi! Lagta hai aapko 'game master' se kuch tips lene padege. 😁",
    "Oye, ek aur zindagi chali gayi! Aapko ab 'game ka chamatkar' dekhna padega! 😅",
    "Arre bhai, ek aur life khatam! Lagta hai aapko game ka 'power-up' milne wala hai. 😎",
    "Aree, ek zindagi aur chali gayi! Lagta hai aapko 'game ki duniya' mein thoda aur 'tashan' lana padega. 😂",
    "Oye, ek life chali gayi! Ab to game ko 'Jabardast' karna padega. 🤣",
    "Arre yaar, ek aur zindagi gayi! Lagta hai aapko ab game ki 'tactics' ko dekhna padega. 😆",
    "Ek aur life chali gayi! Lagta hai game ko ab 'mega hit' banana padega! 😜",
    "Arre, ek zindagi aur kho gayi! Ab to game ke 'raaz' kholne honge. 😁",
    "Arre bhai, ek zindagi aur khatam! Lagta hai aapko ab game mein 'hero' banne ka waqt aa gaya hai! 💪😆",
    "Aree, ek aur zindagi chali gayi! Lagta hai aapko ab game ko 'serious' lena padega. 😂",
    "Oye hoye! Ek life aur chali gayi. Lagta hai aapko 'game ka guru' banne ki zaroorat hai! 🤣",
    "Arre bhai, ek aur life chali gayi! Lagta hai game ko 'full-on' mode mein le jana padega. 😜",
    "Hawww! Ek zindagi aur khatam! Ab game ko 'extra' energy ke saath khelna padega. 😁",
    "Arre, ek aur zindagi chali gayi! Ab to game ko 'dhamal' se bharna padega. 😂",
    "Oh no! You just lost a life. Time to channel your inner Tony Stark and come back stronger! 🦸‍♂️💥",
    "Well, well, well... another life down! Looks like it’s time to assemble your gaming Avengers! 🕷️🦸‍♀️",
    "Whoa! One more life gone! Time to bring out the Bollywood drama and make a blockbuster comeback! 🎬💥",
    "Oops! Lost a life, huh? Time to unleash your inner Bollywood hero and show us the dramatic comeback! 💪🎉",
    "A life lost, just like in a Bollywood movie—now go and give us a heroic comeback with a twist! 🎥💫",
    "Lost a life? Don’t worry, like any superhero, it's time for a powerful comeback. Think of it as your origin story! 🌟🦸",
    "Another life gone? Channel your inner Bollywood star, perform a high-octane comeback, and win the day! 🎭💥",
    "Arre bhai, ek aur zindagi chali gayi! Jaisa Jethalal ke saath hota hai, ab thoda 'tashan' to banta hai! 😆",
    "Arre yaar, ek aur life kho gayi! Jaise Bhide ke saath hota hai, ab ek zabardast comeback karna padega! 😂",
    "Oye, ek zindagi aur chali gayi! Aapko to 'Tapu Sena' ki tarah mil kar game jeetne ka plan banana padega! 😜",
    "Ek aur life khatam! Jaise Daya ke saath hota hai, ab to game mein ek bada dhamaka hona chahiye! 😅",
    "Arre, ek zindagi aur gayi! Jaise Jethalal ne phir se Chappal chhod di, waise aapko game mein 'rebirth' lena padega! 🤣",
    "Arre bhai, ek aur zindagi chali gayi! Jaise Bhide ki planning fail hoti hai, waise aapka plan bhi fail ho gaya! 😆",
    "Oye hoye, ek aur life chali gayi! Jaise Jethalal ko Daya ke saath drama hota hai, aapko bhi game mein drama karna padega! 😂",
    "Arre yaar, ek aur life gayi! Tapu Sena ki tarah, ab ek epic comeback karna padega! 😜",
    "Ek aur zindagi gayi! Jaise Daya ko Jethalal ke jokes nahi samajhte, waise aapko game ka maza nahi aa raha! 😁",
    "Arre bhai, ek aur life chali gayi! Jaisa Jethalal ka naya business fails hota hai, aapko ab game mein 'success' chahiye! 😅",
    "Arre, ek aur zindagi khatam! Jaise Bhide ki homework ki tarah, ab aapko bhi game ko serious lena padega! 😆",
    "Ek aur life gayi! Jaise Daya ke dance moves hamesha epic hote hain, waise aapko bhi game mein epic comeback karna padega! 😂",
    "Arre yaar, ek aur zindagi chali gayi! Jaise Jethalal ki shopping mein hamesha problem hoti hai, waise aapke game mein bhi problem aa gayi! 😜",
    "Oye, ek aur life chali gayi! Jaise Tapu Sena ke antics hamesha funny hote hain, waise aapko bhi game mein funny comeback karna padega! 🤣",
    "Arre bhai, ek aur zindagi gayi! Jaise Bhide ki savings hamesha kam hoti hain, waise aapki lives bhi kam hoti ja rahi hain! 😆",
    "Ek aur life chali gayi! Jaise Jethalal ki madad se Daya ki khushiyan badhati hain, waise aapko ab game mein madad chahiye! 😂",
    "Arre yaar, ek aur zindagi chali gayi! Jaise Tapu Sena ki team hamesha jeet ti hai, waise aapko bhi game mein jeetne ki zaroorat hai! 😜",
]

win_replies = [
    "Arre bhai, sahi jawab diya! Jaise Jethalal ne Daya ko surprise diya, waise aapne game ko surprise victory di! 🎉😆",
    "Oye hoye! Aapne sahi guess kiya! Jaise Bhide ki planning always hits the mark, waise aapki gaming skills bhi top-notch hain! 😎",
    "Arre yaar, aapne to sahi guess kar liya! Tapu Sena ki tarah, aapne bhi game mein dhamaka kar diya! 😜🎊",
    "Wow, sahi guess! Jaise Daya ke dance moves hamesha spectacular hote hain, waise aapki gaming skills bhi zabardast hain! 😁💃",
    "Arre, aapne sahi guess kiya! Jaise Jethalal ka naya business success hota hai, waise aapka game bhi super hit hai! 🎯👏",
    "Aapne to sahi guess kar liya! Jaise Bhide ki homework hamesha perfect hoti hai, waise aapki gameplay bhi perfect thi! 🎉📚",
    "Arre yaar, sahi guess! Jaise Tapu Sena hamesha top hoti hai, waise aap bhi game ke top player ban gaye! 🏆😜",
    "Oye, sahi guess! Jaise Daya ke jokes hamesha smile laaye, waise aapki victory ne sabko khush kar diya! 😄🎉",
    "Arre bhai, aapne sahi guess kiya! Jaise Jethalal ki shopping mein hamesha adventure hota hai, waise aapki victory bhi epic hai! 🛍️😆",
    "Aapne to sahi guess kar liya! Jaise Bhide ki savings badhati hain, waise aapke victory points bhi badh gaye! 💰😎",
    "Arre yaar, sahi guess! Jaise Tapu Sena ki team hamesha jeet ti hai, waise aapne bhi game mein grand win kiya! 🏆🎉",
    "Oye hoye, sahi guess kar liya! Jaise Jethalal aur Daya ka drama hamesha epic hota hai, waise aapki victory bhi epic hai! 😆🌟",
    "Congratulations, superstar! You just aced this game like it's a blockbuster movie! 🎬🏆",
    "You guessed correctly? Wow, you’re the gaming equivalent of a Marvel superhero saving the day! 🦸‍♂️💥",
    "Look at you, guessing correctly like a Bollywood hero in a high-octane climax scene! 🎥💪",
    "Victory achieved! You’re now the lead character in the greatest gaming epic of the year! 🌟🎉",
    "You nailed it! Like a Hollywood star at the Oscars, you’ve just won big! 🏆✨",
    "You guessed correctly! Time to bask in the spotlight like a Bollywood diva at a grand award show! 🌟🎤",
    "So you guessed correctly? Looks like you’ve just pulled off the ultimate Hollywood-style comeback! 🎬🔥",
    "Victory! You’re officially the rockstar of this game, just like a Bollywood blockbuster hero! 🎸🌟",
    "You guessed correctly? Must be nice being the gaming equivalent of a Marvel superhero—unstoppable and epic! 🦸‍♀️💫",
    "Congrats, you’re the MVP! Like a Bollywood film’s hero, you’ve just delivered an epic performance! 🎭💥",
    "Game won! Looks like you’ve just given a performance worthy of a Hollywood award! 🏆🎬",
    "Victory achieved! Looks like you’re the Bollywood blockbuster everyone’s talking about! 🎥⭐",
    "You guessed correctly! Time to do a victory dance like a Bollywood star in a high-energy number! 💃🎉",
    "Winning this game? You're like a Marvel hero in the end credits scene—everyone’s cheering! 🦸‍♂️🎉",
    "Arre bhai, sahi guess! Jaise Jethalal ne Gada Electronics ko chhod diya, waise aapne game ko jeet liya! 📺🏆",
    "Oye hoye! Jaise Bhide ki strictness se sab dar jaate hain, waise aapke gaming skills ne sabko shock kar diya! 😲⚡",
    "Arre yaar, sahi guess! Jaise Tapu Sena ka prank hamesha fun hota hai, waise aapki victory bhi zabardast hai! 🎉🤣",
    "Wow, sahi guess! Jaise Daya ke khana banana hamesha yummy hota hai, waise aapki gaming skills bhi top-class hain! 🍲🌟",
    "Arre, aapne sahi guess kiya! Jaise Jethalal ka naya business idea always a hit hota hai, waise aapka game bhi blockbuster hai! 💡🎯",
    "Aapne to sahi guess kar liya! Jaise Bhide ki classes hamesha well-organized hoti hain, waise aapki gameplay bhi perfect thi! 📚✨",
    "Arre yaar, sahi guess! Jaise Tapu Sena hamesha cool rehti hai, waise aap bhi game ke champion ban gaye! 😎🏆",
    "Oye, sahi guess! Jaise Daya ke memes hamesha viral hote hain, waise aapki victory bhi sabko pasand aayi! 😄🌟",
    "Arre bhai, aapne sahi guess kiya! Jaise Jethalal ke jokes hamesha hansi laate hain, waise aapki victory ne sabko khush kar diya! 😂🎉",
    "Aapne to sahi guess kar liya! Jaise Bhide ki savings se sab impressed hain, waise aapke victory points bhi sabko amaze kar rahe hain! 💰👏",
    "Arre yaar, sahi guess! Jaise Tapu Sena ka teamwork hamesha kamal ka hota hai, waise aapne bhi game mein dhamaka kar diya! 🏆🔥",
    "Oye hoye, sahi guess kar liya! Jaise Jethalal aur Daya ki chemistry hamesha mast hoti hai, waise aapki victory bhi mast hai! 😆💫",
    "Congratulations, superstar! You just nailed it like a meme-worthy moment on Instagram! 📸✨",
    "You guessed correctly? Looks like you’ve just created the ultimate meme moment of the game! 🥳📲",
    "Look at you, winning like the viral sensation everyone’s talking about on Instagram! 📸🎉",
    "Victory achieved! You’re now the hottest topic of the gaming meme world! 🔥🎬",
    "You nailed it! Like a trending Instagram meme, you’ve just gone viral with this win! 📲🌟",
    "You guessed correctly! Time to celebrate like the latest viral dance challenge on Instagram! 💃📸",
    "So you guessed correctly? Looks like you’ve just set a new trend in the gaming world! 🌟🔥",
    "Victory! You’re officially the meme king/queen of this game, just like the hottest trending Instagram star! 👑📸",
    "You guessed correctly? Must be nice being the star of the latest viral meme! 🌟🎥",
    "Congrats, you’re the MVP! Like the hottest Instagram meme, you’ve just delivered an epic performance! 📸🎉",
    "Game won! Looks like you’ve just achieved meme-worthy status in the gaming world! 🎯🔥",
    "Victory achieved! You’re now the talk of the town, just like the latest trending meme! 🗣️🎉",
    "You guessed correctly! Time to shine like a viral Instagram post! 📸💫",
    "Winning this game? You're like the latest meme sensation everyone’s reposting! 🔥📲",
]




