marvel_heroes_with_hints = [
    ("doctorstrange", "Master of the Mystic Arts and the Sorcerer Supreme."),
    ("ironman", "Genius billionaire in an armored suit powered by an arc reactor."),
    ("captainamerica", "Super-soldier with a shield made of vibranium."),
    ("thor", "The god of thunder who wields the hammer Mjolnir."),
    ("hulk", "A scientist who transforms into a green rage monster with immense strength."),
    ("blackwidow", "A highly trained spy and combat expert."),
    ("spiderman", "A young hero with spider-like abilities and web-slinging."),
    ("antman", "Can shrink and grow in size using a special suit."),
    ("hawkeye", "A master archer with precise aim."),
    ("blackpanther", "King of Wakanda with enhanced senses and a vibranium suit."),
    ("scarletwitch", "Possesses powerful chaos magic and reality-warping abilities."),
    ("vision", "An android with the power of flight, density control, and a mind stone."),
    ("falcon", "Uses mechanical wings for flight and is an expert in aerial combat."),
    ("wintersoldier", "A super-soldier with a metal arm and highly trained combat skills."),
    ("captainmarvel", "Possesses cosmic powers and can fly through space."),
    ("starlord", "Leader of the Guardians of the Galaxy, with combat and piloting skills."),
    ("groot", "A sentient tree-like creature with regenerative powers."),
    ("rocketraccoon", "A genetically enhanced raccoon with tech expertise and a love for weapons."),
    ("drax", "A powerful warrior with a personal vendetta against Thanos."),
    ("gamora", "A skilled assassin and the adopted daughter of Thanos."),
    ("nebula", "A cybernetic assassin with a complex relationship with her sister, Gamora."),
    ("loki", "The god of mischief, known for illusion and trickery."),
    ("warmachine", "A military officer in a heavily armed Iron Man-style suit."),
    ("wasp", "A superhero with the ability to shrink and fly, alongside Ant-Man."),
    ("shangchi", "Master of martial arts and the mystical Ten Rings."),
    ("eternals", "An ancient group of immortal beings with various powers.")
]

bollywood_heroes_with_hints = [
    ("shahrukhkhan", "Known as the King of Bollywood, famous for 'Dilwale Dulhania Le Jayenge'."),
    ("salmankhan", "Star of 'Bajrangi Bhaijaan' and 'Sultan'."),
    ("aamirkhan", "Actor in 'Dangal' and '3 Idiots', known for perfection."),
    ("akshaykumar", "Known for action-comedies like 'Housefull' and 'Khiladi'."),
    ("ranveersingh", "A versatile actor known for energetic roles in 'Padmaavat' and 'Gully Boy'."),
    ("hrithikroshan", "A dancing sensation and action star from 'Krrish' and 'War'."),
    ("ranbirkapoor", "Known for roles in 'Sanju' and 'Rockstar'."),
    ("ajaydevgn", "A serious and action-packed actor famous for 'Singham' and 'Tanhaji'."),
    ("amitabhbachchan", "The legendary actor known for 'Sholay' and 'Piku'."),
    ("varundhawan", "Star of 'Badrinath Ki Dulhania' and 'Street Dancer'."),
    ("sidharthmalhotra", "Known for his roles in 'Kapoor & Sons' and 'Shershaah'."),
    ("arjunkapoor", "Notable for performances in '2 States' and 'Namaste England'."),
    ("akshaye", "Famous for his roles in 'Sardar Udham' and 'Pati Patni Aur Woh'."),
    ("karthikaryan", "Known for his roles in 'Pyaar Ka Punchnama' and 'Sonu Ke Titu Ki Sweety'."),
    ("sushantsinghrajput", "Known for 'Chhichhore' and 'MS Dhoni: The Untold Story'."),
    ("saifalikhan", "Famous for roles in 'Omkara' and 'Tanhaji'."),
    ("johnabraham", "Known for his roles in 'Dhoom' and 'Batla House'."),
    ("vivekoberoi", "Notable for his performances in 'Company' and 'Saathiya'."),
    ("emraanhashmi", "Known for his roles in 'Murder' and 'Jannat'."),
    ("shahidkapoor", "Famous for 'Haider' and 'Kabir Singh'."),
    ("hritikroshan", "Renowned for his performances in 'War' and 'Super 30'."),
    ("abhishekbachchan", "Notable for 'Guru' and 'Dhoom'."),
    ("bobbydeol", "Known for roles in 'Soldier' and 'Race 3'."),
    ("sushantsinghrajput", "Famous for his roles in 'Chhichhore' and 'MS Dhoni: The Untold Story'."),
    ("diljeitsingh", "Popular for his roles in 'Punjab 1984' and 'Good Newwz'."),
    ("prabhas", "Known for his work in 'Baahubali' and 'Saaho'."),
    ("nawazuddinsiddiqui", "Renowned for his performances in 'Gangs of Wasseypur' and 'Sacred Games'."),
    ("manojbajpayee", "Famous for his roles in 'Satya' and 'The Family Man'."),
    ("pankajtripathi", "Known for his roles in 'Stree' and 'Mirzapur'."),
    ("zaynmalik", "Not a Bollywood actor but a well-known figure in the entertainment industry."),
    ("salman", "Another name for Salman Khan, star of 'Kick' and 'Bajrangi Bhaijaan'."),
    ("ranvirsingh", "Another spelling for Ranveer Singh, known for 'Padmaavat' and 'Gully Boy'."),
    ("ranbirkapoor", "Another spelling for Ranbir Kapoor, known for 'Rockstar' and 'Sanju'."),
    ("ajay", "Another name for Ajay Devgn, known for 'Tanhaji' and 'Singham'."),
    ("amitabh", "Another name for Amitabh Bachchan, renowned for his roles in 'Sholay' and 'Paa'.")
]

cricketers_with_hints = [
    ("sachintendulkar", "The 'Master Blaster' and one of the greatest batsmen in cricket history."),
    ("viratkohli", "Former captain of the Indian team, known for his aggressive batting style."),
    ("msdhoni", "Captain Cool, famous for his calm demeanor and finishing matches."),
    ("rohitsharma", "Known for his record-breaking double centuries in ODI cricket."),
    ("kapildev", "Legendary all-rounder who led India to its first World Cup victory in 1983."),
    ("yuvrajsingh", "Famous for hitting six sixes in an over and his comeback from cancer."),
    ("rahuldravid", "The 'Wall' of Indian cricket, known for his impeccable technique."),
    ("anilkumble", "India's leading wicket-taker and famous for his spin bowling."),
    ("jaspritbumrah", "A fast bowler known for his unorthodox action and lethal yorkers."),
    ("hardikpandya", "An all-rounder known for his explosive batting and pace bowling."),
    ("ravindrajadeja", "A versatile all-rounder known for his sharp fielding and spin bowling."),
    ("souravganguly", "Former captain and 'Dada' of Indian cricket, known for his aggressive leadership."),
    ("zaheerkhan", "One of India's finest fast bowlers, known for his reverse swing."),
    ("vvsLaxman", "Renowned for his elegant batting and match-saving innings."),
    ("klrahul", "A stylish opening batsman, also known for his wicketkeeping."),
    ("shikhardhawan", "An explosive left-handed opener with a trademark moustache."),
    ("sureshraina", "One of IPL's most consistent performers and an aggressive middle-order batsman."),
    ("dineshkarthik", "A versatile wicketkeeper-batsman, known for his IPL finishing abilities."),
    ("rishabhpant", "A fearless young wicketkeeper-batsman, known for his aggressive play."),
    ("ashwinravichandran", "A world-class off-spinner and a handy lower-order batsman."),
    ("bhuvneshwar", "A fast bowler known for his swing and control, especially in IPL."),
    ("rashidkhan", "An Afghan leg-spinner, a T20 sensation in IPL with his spin variations."),
    ("andrerussell", "A West Indian all-rounder known for his power hitting and fast bowling in IPL."),
    ("davidwarner", "An explosive Australian opener, IPL star with multiple Orange Caps."),
    ("abdevilliers", "Mr. 360, known for his innovative batting shots in IPL and international cricket."),
    ("benstokes", "England's star all-rounder, known for his heroics in all formats of the game."),
    ("patcummins", "A fast bowler from Australia, known for his pace and impact in IPL."),
    ("jofraarcher", "A fast bowler from England, known for his express pace and success in IPL."),
    ("kieronpollard", "A big-hitting West Indian all-rounder, a long-time IPL star with Mumbai Indians."),
    ("quintondekock", "A South African wicketkeeper-batsman known for his aggressive starts in IPL."),
    ("stevesmith", "Former Australian captain, a technically sound batsman, and a key player in IPL."),
    ("kaneWilliamson", "Captain of New Zealand, known for his calm leadership and consistency in IPL."),
    ("sunilnarine", "A West Indian all-rounder, known for his mystery spin and pinch-hitting in IPL."),
    ("trentyboult", "A left-arm fast bowler from New Zealand, known for his swing bowling in IPL."),
    ("shreyasiyer", "A young Indian batsman, former captain of Delhi Capitals in IPL."),
    ("mayankagarwal", "An Indian opener, known for his consistency in IPL and international cricket."),
    ("prithvishaw", "A young Indian batsman known for his aggressive starts in IPL."),
    ("sanjuvijay", "An exciting wicketkeeper-batsman from Kerala, captain of Rajasthan Royals in IPL."),
    ("ravibishnoi", "A young leg-spinner known for his impressive performances in IPL."),
    ("arshdeep", "An emerging left-arm fast bowler known for his death bowling skills in IPL."),
    ("devduttpadikkal", "A young left-handed opener who impressed with his performances in IPL.")
]

