marvel_heroes_with_hints = [
    ("doctorstrange", "Master of the Mystic Arts and the Sorcerer Supreme."),
    ("ironman", "Genius billionaire in an armored suit powered by an arc reactor."),
    ("captainamerica", "Super-soldier with a shield made of vibranium."),
    ("thor", "The god of thunder who wields the hammer Mjolnir."),
    ("hulk", "A scientist who transforms into a green rage monster with immense strength."),
    ("blackwidow", "A highly trained spy and combat expert."),
    ("spiderman", "A young hero with spider-like abilities and web-slinging."),
    ("antman", "Can shrink and grow in size using a special suit."),
    ("hawkeye", "A master archer with precise aim."),
    ("blackpanther", "King of Wakanda with enhanced senses and a vibranium suit."),
    ("scarletwitch", "Possesses powerful chaos magic and reality-warping abilities."),
    ("vision", "An android with the power of flight, density control, and a mind stone."),
    ("falcon", "Uses mechanical wings for flight and is an expert in aerial combat."),
    ("wintersoldier", "A super-soldier with a metal arm and highly trained combat skills."),
    ("captainmarvel", "Possesses cosmic powers and can fly through space."),
    ("starlord", "Leader of the Guardians of the Galaxy, with combat and piloting skills."),
    ("groot", "A sentient tree-like creature with regenerative powers."),
    ("rocketraccoon", "A genetically enhanced raccoon with tech expertise and a love for weapons."),
    ("drax", "A powerful warrior with a personal vendetta against Thanos."),
    ("gamora", "A skilled assassin and the adopted daughter of Thanos."),
    ("nebula", "A cybernetic assassin with a complex relationship with her sister, Gamora."),
    ("loki", "The god of mischief, known for illusion and trickery."),
    ("warmachine", "A military officer in a heavily armed Iron Man-style suit."),
    ("wasp", "A superhero with the ability to shrink and fly, alongside Ant-Man."),
    ("shangchi", "Master of martial arts and the mystical Ten Rings."),
    ("eternals", "An ancient group of immortal beings with various powers.")
]

bollywood_heroes_with_hints = [
    ("shahrukhkhan", "Known as the King of Bollywood, famous for 'Dilwale Dulhania Le Jayenge'."),
    ("salmankhan", "Star of 'Bajrangi Bhaijaan' and 'Sultan'."),
    ("aamirkhan", "Actor in 'Dangal' and '3 Idiots', known for perfection."),
    ("akshaykumar", "Known for action-comedies like 'Housefull' and 'Khiladi'."),
    ("ranveersingh", "A versatile actor known for energetic roles in 'Padmaavat' and 'Gully Boy'."),
    ("hrithikroshan", "A dancing sensation and action star from 'Krrish' and 'War'."),
    ("ranbirkapoor", "Known for roles in 'Sanju' and 'Rockstar'."),
    ("ajaydevgn", "A serious and action-packed actor famous for 'Singham' and 'Tanhaji'."),
    ("amitabhbachchan", "The legendary actor known for 'Sholay' and 'Piku'."),
    ("varundhawan", "Star of 'Badrinath Ki Dulhania' and 'Street Dancer'."),
    ("sidharthmalhotra", "Known for his roles in 'Kapoor & Sons' and 'Shershaah'."),
    ("arjunkapoor", "Notable for performances in '2 States' and 'Namaste England'."),
    ("akshaye", "Famous for his roles in 'Sardar Udham' and 'Pati Patni Aur Woh'."),
    ("karthikaryan", "Known for his roles in 'Pyaar Ka Punchnama' and 'Sonu Ke Titu Ki Sweety'."),
    ("sushantsinghrajput", "Known for 'Chhichhore' and 'MS Dhoni: The Untold Story'."),
    ("saifalikhan", "Famous for roles in 'Omkara' and 'Tanhaji'."),
    ("johnabraham", "Known for his roles in 'Dhoom' and 'Batla House'."),
    ("vivekoberoi", "Notable for his performances in 'Company' and 'Saathiya'."),
    ("emraanhashmi", "Known for his roles in 'Murder' and 'Jannat'."),
    ("shahidkapoor", "Famous for 'Haider' and 'Kabir Singh'."),
    ("hritikroshan", "Renowned for his performances in 'War' and 'Super 30'."),
    ("abhishekbachchan", "Notable for 'Guru' and 'Dhoom'."),
    ("bobbydeol", "Known for roles in 'Soldier' and 'Race 3'."),
    ("sushantsinghrajput", "Famous for his roles in 'Chhichhore' and 'MS Dhoni: The Untold Story'."),
    ("diljeitsingh", "Popular for his roles in 'Punjab 1984' and 'Good Newwz'."),
    ("prabhas", "Known for his work in 'Baahubali' and 'Saaho'."),
    ("nawazuddinsiddiqui", "Renowned for his performances in 'Gangs of Wasseypur' and 'Sacred Games'."),
    ("manojbajpayee", "Famous for his roles in 'Satya' and 'The Family Man'."),
    ("pankajtripathi", "Known for his roles in 'Stree' and 'Mirzapur'."),
    ("zaynmalik", "Not a Bollywood actor but a well-known figure in the entertainment industry."),
    ("salman", "Another name for Salman Khan, star of 'Kick' and 'Bajrangi Bhaijaan'."),
    ("ranvirsingh", "Another spelling for Ranveer Singh, known for 'Padmaavat' and 'Gully Boy'."),
    ("ranbirkapoor", "Another spelling for Ranbir Kapoor, known for 'Rockstar' and 'Sanju'."),
    ("ajay", "Another name for Ajay Devgn, known for 'Tanhaji' and 'Singham'."),
    ("amitabh", "Another name for Amitabh Bachchan, renowned for his roles in 'Sholay' and 'Paa'.")
]

cricketers_with_hints = [
    ("sachintendulkar", "The 'Master Blaster' and one of the greatest batsmen in cricket history."),
    ("viratkohli", "Former captain of the Indian team, known for his aggressive batting style."),
    ("msdhoni", "Captain Cool, famous for his calm demeanor and finishing matches."),
    ("rohitsharma", "Known for his record-breaking double centuries in ODI cricket."),
    ("kapildev", "Legendary all-rounder who led India to its first World Cup victory in 1983."),
    ("yuvrajsingh", "Famous for hitting six sixes in an over and his comeback from cancer."),
    ("rahuldravid", "The 'Wall' of Indian cricket, known for his impeccable technique."),
    ("anilkumble", "India's leading wicket-taker and famous for his spin bowling."),
    ("jaspritbumrah", "A fast bowler known for his unorthodox action and lethal yorkers."),
    ("hardikpandya", "An all-rounder known for his explosive batting and pace bowling."),
    ("ravindrajadeja", "A versatile all-rounder known for his sharp fielding and spin bowling."),
    ("souravganguly", "Former captain and 'Dada' of Indian cricket, known for his aggressive leadership."),
    ("zaheerkhan", "One of India's finest fast bowlers, known for his reverse swing."),
    ("vvsLaxman", "Renowned for his elegant batting and match-saving innings."),
    ("klrahul", "A stylish opening batsman, also known for his wicketkeeping."),
    ("shikhardhawan", "An explosive left-handed opener with a trademark moustache."),
    ("sureshraina", "One of IPL's most consistent performers and an aggressive middle-order batsman."),
    ("dineshkarthik", "A versatile wicketkeeper-batsman, known for his IPL finishing abilities."),
    ("rishabhpant", "A fearless young wicketkeeper-batsman, known for his aggressive play."),
    ("ashwinravichandran", "A world-class off-spinner and a handy lower-order batsman."),
    ("bhuvneshwar", "A fast bowler known for his swing and control, especially in IPL."),
    ("rashidkhan", "An Afghan leg-spinner, a T20 sensation in IPL with his spin variations."),
    ("andrerussell", "A West Indian all-rounder known for his power hitting and fast bowling in IPL."),
    ("davidwarner", "An explosive Australian opener, IPL star with multiple Orange Caps."),
    ("abdevilliers", "Mr. 360, known for his innovative batting shots in IPL and international cricket."),
    ("benstokes", "England's star all-rounder, known for his heroics in all formats of the game."),
    ("patcummins", "A fast bowler from Australia, known for his pace and impact in IPL."),
    ("jofraarcher", "A fast bowler from England, known for his express pace and success in IPL."),
    ("kieronpollard", "A big-hitting West Indian all-rounder, a long-time IPL star with Mumbai Indians."),
    ("quintondekock", "A South African wicketkeeper-batsman known for his aggressive starts in IPL."),
    ("stevesmith", "Former Australian captain, a technically sound batsman, and a key player in IPL."),
    ("kanewilliamson", "Captain of New Zealand, known for his calm leadership and consistency in IPL."),
    ("sunilnarine", "A West Indian all-rounder, known for his mystery spin and pinch-hitting in IPL."),
    ("trentboult", "A left-arm fast bowler from New Zealand, known for his swing bowling in IPL."),
    ("shreyasiyer", "A young Indian batsman, former captain of Delhi Capitals in IPL."),
    ("mayankagarwal", "An Indian opener, known for his consistency in IPL and international cricket."),
    ("prithvishaw", "A young Indian batsman known for his aggressive starts in IPL."),
    ("sanjusamson", "An exciting wicketkeeper-batsman from Kerala, captain of Rajasthan Royals in IPL."),
    ("ravibishnoi", "A young leg-spinner known for his impressive performances in IPL."),
    ("arshdeep", "An emerging left-arm fast bowler known for his death bowling skills in IPL."),
    ("devduttpadikkal", "A young left-handed opener who impressed with his performances in IPL.")
]

indian_cities_with_hints = [
    ("mumbai", "Financial Capital Of India"),
    ("delhi", "Capital Of India"),
    ("bengaluru", "Silicon Valley Of India"),
    ("chennai", "Gateway To South India"),
    ("hyderabad", "City Of Pearls"),
    ("kolkata", "City Of Joy"),
    ("pune", "Oxford Of The East"),
    ("ahmedabad", "Textile Hub Of India"),
    ("jaipur", "Pink City Of Rajasthan"),
    ("surat", "Diamond City"),
    ("lucknow", "City Of Nawabs"),
    ("chandigarh", "Planned City"),
    ("varanasi", "Spiritual Capital Of India"),
    ("amritsar", "Golden Temple City"),
    ("thiruvananthapuram", "Evergreen City Of India"),
    ("kochi", "Queen Of The Arabian Sea"),
    ("mysuru", "City Of Palaces"),
    ("indore", "Cleanest City"),
    ("guwahati", "Gateway To Northeast"),
    ("nagpur", "Orange City"),
    ("patna", "Ancient City"),
    ("bhopal", "City Of Lakes"),
    ("agra", "City Of The Taj Mahal"),
    ("shimla", "Queen Of Hills"),
    ("coimbatore", "Manchester Of India"),
    ("udaipur", "City Of Lakes In Rajasthan"),
    ("vadodara", "Cultural Capital Of Gujarat"),
    ("rajkot", "City Of Saurashtra"),
    ("jodhpur", "Blue City, Mehrangarh Fort"),
    ("madurai", "Temple City, Meenakshi Temple"),
    ("nashik", "Winery Of India, Trimbakeshwar Temple"),
    ("kanpur", "Leather City"),
    ("allahabad", "City Of Triveni, Sangam"),
    ("tiruchirappalli", "Rockfort City, Srirangam Temple"),
    ("aurangabad", "City Of Gates, Ajanta And Ellora Caves"),
    ("ranchi", "City Of Falls, Hundru Falls"),
    ("jamshedpur", "Steel City, Jubilee Park"),
    ("dhanbad", "Coal Capital Of India"),
    ("dehradun", "Doon Valley, Forest Research Institute"),
    ("raipur", "Capital Of Chhattisgarh"),
    ("noida", "IT City"),
    ("ghaziabad", "Industrial Hub Of UP"),
    ("vijayawada", "Business Capital Of Andhra Pradesh"),
    ("visakhapatnam", "City Of Density, RK Beach"),
    ("gwalior", "City Of Forts, Gwalior Fort"),
    ("ludhiana", "Manchester Of India"),
    ("meerut", "Sports Goods Manufacturing Hub"),
    ("salem", "Mangoes And Steel City, Yercaud"),
    ("jabalpur", "City Of Marble, Marble Rocks"),
    ("belagavi", "Sugar Bowl, Kittur Fort"),
    ("rourkela", "Steel City Of Odisha, Hanuman Vatika"),
    ("ajmer", "Holy City, Ajmer Sharif Dargah"),
    ("pondicherry", "French Riviera Of The East, Auroville"),
    ("srinagar", "Paradise On Earth, Dal Lake"),
    ("leh", "Highest Settlement, Pangong Lake"),
    ("shillong", "Scotland Of The East, Elephant Falls"),
    ("imphal", "Jewel Of India, Loktak Lake"),
    ("aizawl", "Land Of Highlanders"),
    ("gangtok", "Buddhist Pilgrimage, Rumtek Monastery")
]

indian_historical_places_with_hints = [
    ("tajmahal", "Agra - Built By Shah Jahan In Memory Of Mumtaz"),
    ("redfort", "Delhi - Mughal Residence And Military Headquarters"),
    ("qutubminar", "Delhi - Tallest Brick Minaret In The World"),
    ("indiagate", "Delhi - War Memorial For Soldiers Of World War I"),
    ("gatewayofindia", "Mumbai - Commemorates King George V's Visit To India"),
    ("amerfort", "Jaipur - Known For Its Artistic Hindu Architecture"),
    ("hawamahal", "Jaipur - Palace Of Winds With 953 Windows"),
    ("victoriamemorial", "Kolkata - Memorial To Queen Victoria Of Britain"),
    ("charminar", "Hyderabad - Built To Commemorate The End Of A Plague"),
    ("suntemple", "Konark - 13th Century Temple Dedicated To The Sun God"),
    ("khajurahotemples", "Madhya Pradesh - Famous For Erotic Sculptures"),
    ("sanchistupa", "Madhya Pradesh - Built By Emperor Ashoka, Buddhist Relic"),
    ("ajantacaves", "Maharashtra - Ancient Buddhist Cave Paintings And Sculptures"),
    ("elloracaves", "Maharashtra - Rock-Cut Temples And Monasteries"),
    ("mehraulianarchaeologicalpark", "Delhi - Contains Ruins From Several Historical Eras"),
    ("golcondafort", "Hyderabad - Known For Its Acoustic Effects"),
    ("mysorepalace", "Mysuru - Former Residence Of Wodeyar Dynasty"),
    ("fatehpursikri", "Uttar Pradesh - Mughal Emperor Akbar's Capital City"),
    ("raniikavav", "Gujarat - UNESCO World Heritage Stepwell"),
    ("chittorgarhfort", "Rajasthan - Largest Fort In India, Known For Its History Of Valor"),
    ("jallianwalabagh", "Amritsar - Site Of The 1919 Massacre During British Rule"),
    ("brihadeeswarartemple", "Tamil Nadu - Chola Dynasty Temple, UNESCO Site"),
    ("gwaliorfort", "Madhya Pradesh - Historic Fort With Intricate Architecture"),
    ("ranthamborefort", "Rajasthan - Famous Fort Inside A Wildlife Sanctuary"),
    ("elephantacaves", "Mumbai - Ancient Hindu Cave Sculptures"),
    ("ruinsofhampi", "Karnataka - Ancient City, Capital Of Vijayanagara Empire"),
    ("jantarmantar", "Jaipur - Collection Of Astronomical Instruments"),
    ("sabarmatiashram", "Ahmedabad - Mahatma Gandhi's Home And Headquarters"),
    ("nalanduniversity", "Bihar - Ancient Center Of Learning And Buddhism"),
    ("golgumbaz", "Bijapur - Second Largest Dome In The World"),
    ("jogfalls", "Karnataka - One Of The Highest Waterfalls In India"),
    ("cellularjail", "Andaman Islands - Used By British For Political Prisoners"),
    ("raghuwarfort", "Chhattisgarh - Historic Fort With Rich History"),
    ("badshahibagh", "Agra - Mughal Garden With Beautiful Landscapes"),
    ("durgabari", "Silchar - Historical Temple Dedicated To Goddess Durga"),
    ("srirangamtemple", "Tiruchirappalli - Famous Vaishnavite Temple Complex"),
    ("madhuratemple", "Kerala - Temple Known For Its Architectural Splendor"),
    ("seemachalamtemple", "Visakhapatnam - Ancient Temple Dedicated To Varaha Lakshmi Narasimha"),
    ("kumbhalgarhfort", "Rajasthan - Known For Its Impressive Fortifications"),
    ("sahastra lingatemple", "Bagalkot - Temple With Thousand Lingas"),
    ("shantiastupa", "Rajgir - Buddhist Stupa Built By The Japanese"),
    ("rajarani temple", "Bhubaneswar - Ancient Hindu Temple Known For Its Architecture"),
    ("kailasanathtemple", "Kanchipuram - Historic Temple From The Pallava Dynasty"),
    ("sabarimala", "Kerala - Famous Pilgrimage Site In The Western Ghats"),
    ("siddhivinayaktemple", "Mumbai - Popular Ganesh Temple"),
    ("krishna temple", "Udupi - Important Pilgrimage Site For Followers Of Krishna"),
    ("ahmedshahi", "Jaipur - Mughal Period Monument Known For Its Historical Importance"),
    ("pattadakal", "Karnataka - UNESCO World Heritage Site With Chalukyan Temples"),
    ("raigadh", "Maharashtra - Fort Associated With Chhatrapati Shivaji Maharaj"),
    ("shillong", "Shillong - Famous For Its Beautiful Waterfalls"),
    ("mandu", "Madhya Pradesh - Fort City With Rich Historical Significance"),
    ("kalapathar", "Andaman - Known For Its Scenic Beauty And Historical Importance")
]

indian_cuisines_with_hints = [
    ("biryani", "A RICE DISH WITH SPICES, ORIGINATING FROM HYDERABAD"),
    ("samosa", "FRIED PASTRY FILLED WITH SPICED POTATOES"),
    ("dosa", "A TYPE OF THIN CREPE FROM SOUTH INDIA"),
    ("butterchicken", "CREAMY CHICKEN CURRY FROM PUNJAB"),
    ("idli", "STEAMED RICE CAKES FROM SOUTH INDIA"),
    ("paneerbuttermasala", "COTTAGE CHEESE IN A CREAMY TOMATO SAUCE"),
    ("cholebhature", "SPICY CHICKPEAS SERVED WITH FRIED BREAD"),
    ("pavbhaji", "MIXED VEGETABLE CURRY SERVED WITH BUTTERED BREAD"),
    ("dalmakhani", "LENTIL DISH FROM PUNJAB, COOKED WITH BUTTER"),
    ("vada", "SPICY DEEP FRIED SNACK FROM SOUTH INDIA"),
    ("ragdapattice", "SPICY POTATO CAKES WITH A CHICKPEA CURRY"),
    ("kebab", "GRILLED MEAT OR VEGETABLES MARINATED IN SPICES"),
    ("kheer", "SWEET RICE PUDDING COOKED WITH MILK AND DRIED FRUITS"),
    ("poha", "FLATTENED RICE COOKED WITH SPICES AND VEGETABLES"),
    ("pulao", "RICE DISH COOKED WITH SPICES AND VEGETABLES"),
    ("kulfi", "INDIAN ICE CREAM MADE WITH MILK AND FLAVORS"),
    ("bhelpuri", "PUFFED RICE MIXED WITH VEGETABLES AND CHUTNEYS"),
    ("aalotikki", "SPICY POTATO PATTIES OFTEN SERVED WITH CHUTNEY"),
    ("panchmeldal", "MIXED LENTIL CURRY FROM RAJASTHAN"),
    ("daltadka", "LENTIL DISH TEMPERED WITH SPICES AND GHEE"),
    ("aalogobhi", "POTATO AND CAULIFLOWER CURRY"),
    ("kachori", "SPICY FILLED PASTRY OFTEN SERVED AS A SNACK"),
    ("misalpav", "SPICY BEAN CURRY SERVED WITH BREAD"),
    ("khichdi", "RICE AND LENTIL DISH COOKED TOGETHER"),
    ("tandoorichicken", "CHICKEN MARINATED IN YOGURT AND SPICES THEN GRILLED"),
    ("pithla", "SPICY GRAM FLOUR CURRY FROM MAHARASHTRA"),
    ("dhokla", "STEAMED SAVORY CAKE FROM GUJARAT"),
    ("kothimbirvadi", "CORIANDER AND SPICE FLAVORED SNACK FROM MAHARASHTRA"),
    ("prawncurry", "SPICY CURRY MADE WITH PRAWNS"),
    ("sambhar", "TANGY LENTIL STEW FROM SOUTH INDIA"),
    ("khoya", "MILK SOLIDS USED IN SWEETS AND DESSERTS")
]

